version: 2.17
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
      - run:
          name: Install Node dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh $USER@$IP;
      - run:
          name: Redirect to directory
          command: cd /home/express-mysql-boilerplate
      - run:
          name: Pull the latest build
          command: git pull
      - run:
          name: Restart Web Server
          command: pm2 restart express_api 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build