version: 2.17
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{checksum "yarn.json"}}
      - run:
          name: Install 
          command: yarn
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh $USER@$IP "cd /home/express-api-base; git pull; pm2 restart express_api";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build